name: Update Infra
on:
  push:
    branches:
      - main

jobs:
  init:
    name: Init job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy CloudFormation stack
      uses: aws-actions/aws-cloudformation-deploy@v2
      with:
        template: ./tempaltes/ec2.yaml
        stack-name: my-cloudformation-stack
        capabilities: CAPABILITY_IAM 

