name: Update Infra to Desired State
on:
  push:
    branches:
      - main

jobs:
  init:
    name: Update Infra to Desired State
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy CloudFormation Stacks
      run: ./deploy.sh  # Replace with actual script path if not in same directory

