name: Deploy/Delete Resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action'
        required: true
        options:
          - create/update
          - delete
      type:
        type: choice
        description: 'Run Type'
        required: true
        options:
          - infra
          - helm-charts
      env:
        type: choice
        description: 'Environment'
        required: true
        options:
          - DEV
          - QA
          - PROD
          - UAT

env:
  region: ${{ vars.AWS_REGION }}
  accesskey: ${{ vars.AWS_ACCESS_KEY_ID }}
  secretkey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  init:
    name: Init job
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
    - name: Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.accesskey }}
        aws-secret-access-key: ${{ env.secretkey }}
        aws-region: ${{ env.region }}

