name: Deploy/Delete Resources Manually

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action'
        required: true
        options:
          - create/update
          - delete
      # type:
      #   type: choice
      #   description: 'Run Type'
      #   required: true
      #   options:
      #     - infra
      #     - helm-charts
      # env:
      #   type: choice
      #   description: 'Environment'
      #   required: true
      #   options:
      #     - DEV
      #     - QA
      #     - PROD
      #     - UAT

env:
  region: ${{ vars.AWS_REGION }}
  accesskey: ${{ vars.AWS_ACCESS_KEY_ID }}
  secretkey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Create:
    name: Update Infra to Desired State
    if: github.event.inputs.action == 'create/update'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Change Permission
      run: chmod +x ./deploy.sh

    - name: Deploy CloudFormation Stacks
      run: ./deploy.sh 

  Destroy:
    name: Destroy the Resources
    if: github.event.inputs.action == 'delete'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Change Permission
      run: chmod +x ./destroy.sh

    - name: Deploy CloudFormation Stacks
      run: ./destroy.sh 


