name: Deploy/Delete Resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action'
        required: true
        options:
          - create/update
          - delete
      # type:
      #   type: choice
      #   description: 'Run Type'
      #   required: true
      #   options:
      #     - infra
      #     - helm-charts
      # env:
      #   type: choice
      #   description: 'Environment'
      #   required: true
      #   options:
      #     - DEV
      #     - QA
      #     - PROD
      #     - UAT

env:
  region: ${{ vars.AWS_REGION }}
  accesskey: ${{ vars.AWS_ACCESS_KEY_ID }}
  secretkey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Create/Update:
    name: Update Infra to Desired State
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy CloudFormation stacks
      run: |
        for template in $(find templates -name '*.yaml' -o -name '*.yml'); do
          aws cloudformation deploy \
            --template-file $template \
            --stack-name "${{ vars.AWS_REGION }}-stack-$(basename $template .yaml)" \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
        done

  Destroy:
    name: Destroy the Resources
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}


