name: Pre-Merge Validation

on:
  pull_request:
    branches:
      - main

env:
  region: ${{ vars.AWS_REGION }}
  accesskey: ${{ secrets.AWS_ACCESS_KEY_ID }}
  secretkey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  validate-cloudformation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.accesskey }}
        aws-secret-access-key: ${{ env.secretkey }}
        aws-region: ${{ env.region }}
        
    - name: Validate CloudFormation templates
      id: validate
      run: |
        for template in $(find templates -name '*.yaml' -o -name '*.yml'); do
          aws cloudformation validate-template --template-body file://$template
        done

    - name: Set validation status
      if: ${{ steps.validate.outcome == 'success' }}
      run: echo "::set-output name=validation_status::success"